# Generated by Django 5.1.2 on 2024-10-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="named_url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Named URL"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="slug",
            field=models.SlugField(default="ok", verbose_name="Slug"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="URL"
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="slug",
            field=models.SlugField(default="ok", unique=True, verbose_name="Slug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.SlugField(max_length=255, verbose_name="Name"),
        ),
    ]
