# Generated by Django 5.1.2 on 2024-10-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_item_named_url_item_slug_item_url_menu_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="slug",
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=127, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="item",
            name="named_url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Named URL"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="name",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
    ]
