# Generated by Django 5.1.2 on 2024-10-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_remove_menu_slug_alter_item_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=255, null=True, verbose_name="Slug"
            ),
        ),
    ]
